name: Weekly Update TMDB Collections

on:
  schedule:
    - cron: "0 12 * * 0" # Every Sunday at 12 PM
  workflow_dispatch:

jobs:
  update-collection-ids:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download gzipped JSON file
        run: |
          curl -L -o collection_ids.json.gz http://files.tmdb.org/p/exports/collection_ids_$(date +\%m_%d_%Y).json.gz && touch download_complete
      - name: Wait for download to complete
        run: |
          while [ ! -f download_complete ]; do sleep 1; done
      - name: Check if downloaded file exists
        run: |
          if [ -f collection_ids.json.gz ]; then
            gunzip collection_ids.json.gz
          else
            echo "Error: Downloaded file not found"
            exit 1
          fi
      - name: Copy JSON file to src/assets
        run: |
          cp collection_ids.json src/assets/collection_ids.json
      - name: Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Commit and push changes
        run: |
          git checkout dev
          git add src/assets/collection_ids.json
          git commit -m "chore(assets)[github-actions] : Update collection_ids.json"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update collection_ids.json"
          title: "chore(assets)[github-actions] : Update collection_ids.json"
          body: "Automatically updating collection_ids.json file"
          labels: "📦 dependencies"
          branch: dev
